Redistribute sae
chapinhall/elpep pull request #10
Opened 2023-12-18 19:51 UTC by nsmader

This is a range of commits which primarily:

1. implements an alternative to the Small Area Estimation methods for producing estimates of income-to-poverty rates
2. has adaptations for running estimates for previous base years

2023-12-19 20:52 UTC, kang-hyein requested changes
See comments

2023-12-19 20:52 UTC, kang-hyein commented on run--02a--run-and-validate-SAE.Rmd
>  # Our current specification of `work_incpov_statushs` embeds this alignment
Change to `work_incpov_mix`?

2023-12-19 20:52 UTC, kang-hyein commented on run--02a--run-and-validate-SAE.Rmd
Just noticed in line 204 it's `incpov_6to11_r`. Should this be `incpov_6to12`?

2023-12-19 20:52 UTC, kang-hyein commented on run--02a--run-and-validate-SAE.Rmd
> -```{r save SAE ingredients}
We actually need part of this chunk, saving if rerun_sae is TRUE and loading if rerun_sae is FALSE. Otherwise the next chunks would not run.

2023-12-19 20:52 UTC, kang-hyein commented on run--02a--run-and-validate-SAE.Rmd
> +                       sae_age == "612" ~ "6to11")
I'm assuming this is related to the earlier comment for line 204, is there any reason we do `6to11` instead of `6to12`?

2023-12-20 18:58 UTC, nsmader commented on run--01a--prep-geo-data.Rmd
> +  #
You mean: add this as a reference in the comments?

2023-12-20 19:18 UTC, kang-hyein commented on run--01a--prep-geo-data.Rmd
> +  #
Yes

2023-12-27 17:51 UTC, kang-hyein approved these changes

2023-12-27 18:38 UTC, merged